WITH MAX_PRICE AS (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
)
SELECT PRODUCT_ID
    , PRODUCT_NAME
    , PRODUCT_CD
    , CATEGORY
    , PRICE
FROM FOOD_PRODUCT, MAX_PRICE
WHERE PRICE = MAX_PRICE