WITH HOUR_LIST AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    FROM ANIMAL_OUTS
)
SELECT HOUR
    , COUNT(HOUR) AS COUNT
FROM HOUR_LIST
WHERE HOUR BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR